# WebLogic workaround
spring.profiles.active: weblogic

# SICCON
siccon:
  pcrf:
    host: siccon_legado_pcrf:8080
    uri: http://${siccon.pcrf.host}/axis/services/MessageService
    username: admin
    password: admin
    retry:
      max-attempts: 3
      interval: 10000

# Server
server:
  port: 17001

# Spring
spring:
  jms:
    listener:
      concurrency: 4
      max-concurrency: 10
    template:
      delivery-mode: NON_PERSISTENT
      time-to-live: 60000
      receive-timeout: 60000
  cache:
    type: REDIS
  redis:
    host: localhost
    port: 6379

# Actuator
management:
  security:
    # Allow actuator endpoints to be accessed without requiring authentication
    enabled: false

# Logging
logging:
  file: /xdr/logs/wrapper_pcrf_service.log
  file.max-history: 30
  pattern:
    level: '[correlationId=%X{correlationId}:msisdn=%X{msisdn}] %5p'

---
# WebLogic
spring.profiles: weblogic
spring.profiles.include:
  - jms-jndi

---
# JackSparrow
spring.profiles: jacksparrow
spring.profiles.include:
  - jms-activemq
spring.port: 8081
---
# JMS - ActiveMQ
spring:
  profiles: jms-activemq
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: Tel2012

---
# JMS - JNDI
spring:
  profiles: jms-jndi
  jms:
    jndi-name: jms/JmsConnectionFactory
